name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Check formatting"
        run: "forge fmt --check"

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Run Forge build"
        run: "forge build"
        id: "build"

      - name: "Run Forge test"
        run: "FOUNDRY_PROFILE=ci forge test -vvv"
        id: "test"
